---
- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - prometheus_configure
    - prometheus_install
    - prometheus_run
- block:
    - name: include preflight
      include_tasks: preflight.yml
      tags:
        - prometheus_configure
        - prometheus_install
        - prometheus_run
    - name: include install
      include_tasks: install.yml
      tags:
        - prometheus_install
    - name: include configure
      include_tasks: configure.yml
      tags:
        - prometheus_configure
  become: true
- name: ensure prometheus service is started and enabled
  become: true
  systemd:
    daemon_reload: true
    name: prometheus
    state: started
    enabled: true
  tags:
    - prometheus_run
